### PR TITLE
fixes of usage of bfd to work with binutils>=2.28

### PR DESCRIPTION
**Pull request by omgold**
It seems the API of bfd was slightly changed as of binutils 2.28. This patch makes the project to compile again.

### CODE REVIEW

**Comment by CarloWood** [comment]
I trusted you and just merged it.. but you broke versions prior to binutils 2.28 with this. That's hardly an improvement.

**Comment by omgold** [comment]
Ah, sorry. I wasn't aware that you still need it to work with old binutils. The bfd API simply changed, so I thought it was obvious that it won't work with both (without autoconf/preprocessor #if thingies).

**Comment by CarloWood** [comment]
I am using ubuntu stable and it still uses version 2.26.  Can I remove those #include "config.h"'s? I don't see how they are related to the change in binutils 2.28 and they seem unused.

**Comment by omgold** [comment]
It seems to be another issue that was introduced with newer binutils. If I don't add these, I get a compilation error:

`make[3]: Entering directory '/home/omangold/tmp/libmemleak/src'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I./include   -g -O2 -MT addr2line.lo -MD -MP -MF .deps/addr2line.Tpo -c -o addr2line.lo addr2line.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./include -g -O2 -MT addr2line.lo -MD -MP -MF .deps/addr2line.Tpo -c addr2line.c  -fPIC -DPIC -o .libs/addr2line.o
In file included from addr2line.c:31:0:
/usr/include/bfd.h:35:2: error: #error config.h must be included before this header
 #error config.h must be included before this header
  ^~~~~`

**Comment by CarloWood** [comment]
Ok, can you please test my latest pushed commit?

**Comment by CarloWood** [comment]
Note that you need to rerun ./autogen.sh in order to get the new autoconf macro to be imported.

**Comment by CarloWood** [comment]
In your case you should get from configure:
checking if bfd_error_handler_type is printf style... no
